apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: payments-pre-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/kargobook/demo-gitops.git
    targetRevision: main
    path: apps/payments/envs/pre-prod
  destination:
    server: https://kubernetes.default.svc
    namespace: payments-pre-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
