apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-prod
resources:
- ../../base
images:
- name: ghcr.io/genekuo-org/demo-app
  digest: sha256:cdcec357189623f9049b14528e92aca020aedc257ec0fe83c264389411e64d39
