apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: demo-pre-prod
resources:
- ../../base
images:
- name: ghcr.io/genekuo-org/demo-app
  digest: sha256:8c3999764661207663636226f0ac81635429d2ead91c8e56717335b69ab1fe38
